name: Switch Node version
on: 
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name : setup node
          id: toto
          uses: actions/setup-node@v3
          with:
            node-version: '14'
        - name: run test
          shell: bash
          run: |
            echo ${{ steps.toto.outputs.node-version }}
            npm install
            npm test
